services:
  web:
    build: .
    container_name: dreamin
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_files:/app/media
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres

  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d database"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  media_files: