version: '3.8'

services:
  web:
    build: .
    command: gunicorn dreamin.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://dreamin_owner:yVRMfOpx1H3L@ep-floral-violet-a1ak1di7.ap-southeast-1.aws.neon.tech/dreamin?sslmode=require
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - CLOUDINARY_CLOUD_NAME=dysfn8kdg
      - CLOUDINARY_API_KEY=435326248528675
      - CLOUDINARY_API_SECRET=ZlmokmXJXPveQ0VVxTodkaGxoJY

volumes:
  static_volume: