# Generated by Django 5.1.3 on 2024-12-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to='dream_previews/'),
        ),
    ]
