# Generated by Django 5.1.4 on 2024-12-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sound_file', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dream',
            name='dialogue',
        ),
        migrations.AddField(
            model_name='dream',
            name='dialogues',
            field=models.ManyToManyField(blank=True, to='main.dialogue'),
        ),
    ]
