# Generated by Django 5.1.4 on 2024-12-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dream_preview_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
