# Generated by Django 5.1.4 on 2024-12-20 08:41

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_last_session_key_profile_login_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamanimation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='animations/', validators=[main.models.validate_file_size, main.models.validate_file_extension]),
        ),
    ]
