# Generated by Django 5.0 on 2024-12-21 01:08

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_dreamanimation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='dialogues'),
        ),
        migrations.AlterField(
            model_name='dreamanimation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='animations', validators=[main.models.validate_file_size, main.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='dreamsound',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='sounds'),
        ),
    ]
