# Generated by Django 5.0 on 2024-12-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_dialogue_file_alter_dreamanimation_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
